apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primes-service
  template:
    metadata:
      labels:
        app: primes-service
    spec:
      containers:
        - name: primes
          image: practicums.azurecr.io/primes-service:April08
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: primes-service
spec:
  selector:
    app: primes-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  url: jdbc:postgresql://p466-postgres-server.postgres.database.azure.com:5432/primes?sslmode=require
  username: admin410
  password: p466password321!

