name: Deploy Primes Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: primes
          POSTGRES_USER: admin410
          POSTGRES_PASSWORD: p466password321!
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_UN: ${{ secrets.SPRING_DATASOURCE_UN }}
      SPRING_DATASOURCE_PW: ${{ secrets.SPRING_DATASOURCE_PW }}
      SERVICE_VERSION: ${{ secrets.SERVICE_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build app
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: ./scripts/build-image.sh

      - name: Push to GitHub Container Registry
        run: ./scripts/push-to-ghcr.sh

      - name: Push to Azure Container Registry
        run: ./scripts/push-to-acr.sh

      - name: Setup Kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to AKS
        run: ./scripts/deploy.sh

      # Add the `distribution` input for docker build-push-action if it's used here:
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/YOUR_USERNAME/your-image:latest
          distribution: linux/amd64  # <- This is the missing input
