name: Deploy Primes Service
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh
        
      - name: Build Docker image
        run: ./scripts/build-image.sh
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to GitHub Container Registry
        run: ./scripts/push-to-ghcr.sh
        
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Push to Azure Container Registry
        run: ./scripts/push-to-acr.sh
        
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure Kubernetes credentials
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          
      - name: Deploy to AKS
        run: ./scripts/deploy.sh